---
- name: MY AS3 PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    uri_method: POST

  vars_files:
    - ../creds/big_creds.yaml

  tasks:

  - name: Brocks- Deploy AS3 Declarative
    uri:
      url: https://35.176.27.123/mgmt/shared/appsvcs/declare
      user: "{{ bigip_user }}"
      password: "{{ bigip_pass }}"
      method: "{{ uri_method }}"
      body: "{{ lookup('file','as3-declaration.json') }}"
      validate_certs: false
      force_basic_auth: yes
      status_code: 200
      body_format: json
    register: as3_response

  - name: AS3 RESPONSE OUTPUT
    debug:
      msg: "{{as3_response }}"
      
...